pipeline {
    agent any

    environment {
        GIT_REPO_URL = 'https://github.com/gitmaster-dms/Spero-DMS.git'  
        GIT_BRANCH = 'main'  
        TARGET_DIR  = '/var/www/html/Aggregation_test_project/DMS_goa_test'
    }

    stages {
        stage('Clone or Pull Repository') {
            steps {
                script {
                    // Check if the directory already exists
                    if (!fileExists(TARGET_DIR)) {
                        // If the directory doesn't exist, clone the repository
                        echo "Cloning repository to $TARGET_DIR..."
                        sh "git clone -b ${GIT_BRANCH} ${GIT_REPO_URL} ${TARGET_DIR}"
                    } else {
                        // If the directory exists, perform a pull
                        echo "Repository already exists. Pulling latest changes..."
                        dir(TARGET_DIR) {
                            sh "git pull origin ${GIT_BRANCH}"
                        }
                    }
                }
            }
        }

        stage('Check Files') {
            steps {
                sh "ls -al ${TARGET_DIR}"  
            }
        }

        stage('Setup Python Virtual ENV for dependencies') {
            steps {
                sh '''
                    echo "Checking current workspace directory"
                    echo $PWD
                    chmod +x ${TARGET_DIR}/Deployment/envsetup.sh
                    ${TARGET_DIR}/Deployment/envsetup.sh
                '''
            }
        }

        stage('Setup Gunicorn Setup') {
            steps {
                sh '''
                    chmod +x ${TARGET_DIR}/Deployment/gunicorn.sh
                    ${TARGET_DIR}/Deployment/gunicorn.sh
                '''
            }
        }

        stage('Setup NGINX') {
            steps {
                sh '''
                    chmod +x ${TARGET_DIR}/nginx.sh
                    ${TARGET_DIR}/Deployment/nginx.sh
                '''
            }
        }
    }

    post {
        success {
            echo 'Build was successful!'
        }

        failure {
            echo 'Build failed. Please check the logs.'
        }
    }
}