pipeline {
    agent any

    environment {
        GIT_REPO_URL = 'https://github.com/gitmaster-dms/Spero-DMS.git'  
        GIT_BRANCH = 'main'  
    }

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    if (!fileExists('.git')) {
                        // If repository is not cloned, clone it
                        echo "Repository not found. Cloning..."
                        git url: GIT_REPO_URL, branch: GIT_BRANCH
                    } else {
                        // If already cloned, perform a pull
                        echo "Repository already cloned. Pulling latest changes..."
                        sh 'git pull origin $GIT_BRANCH'
                    }
                }
            }
        }

        stage('Check Files') {
            steps {
                sh 'ls -al'
            }
        }

        stage('Setup Python Virtual ENV for dependencies') {
            steps {
                sh '''
                    echo "Checking current workspace directory"
                    #ls -al
                    echo $PWD
                    chmod +x envsetup.sh
                    ./envsetup.sh
                '''
            }
        }

        stage('Setup Gunicorn Setup') {
            steps {
                sh '''
                    chmod +x gunicorn.sh
                    ./gunicorn.sh
                '''
            }
        }

        stage('Setup NGINX') {
            steps {
                sh '''
                    chmod +x nginx.sh
                    ./nginx.sh
                '''
            }
        }
    }

    post {
        success {
            echo 'Build was successful!'
        }

        failure {
            echo 'Build failed. Please check the logs.'
        }
    }
}
