# Generated by Django 5.0.4 on 2025-05-07 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMS_Employee',
            fields=[
                ('emp_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('emp_username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('emp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('emp_email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('emp_dob', models.DateField(blank=True, null=True)),
                ('emp_doj', models.DateField(blank=True, null=True)),
                ('emp_is_login', models.BooleanField(blank=True, default=False, null=True)),
                ('grp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dist_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tahsil_id', models.CharField(blank=True, max_length=255, null=True)),
                ('city_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('emp_is_deleted', models.BooleanField(default=False)),
                ('emp_added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('emp_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DMS_City',
            fields=[
                ('cit_id', models.AutoField(primary_key=True, serialize=False)),
                ('cit_name', models.CharField(max_length=255)),
                ('cit_is_deleted', models.BooleanField(default=False)),
                ('cit_added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cit_added_date', models.DateTimeField(auto_now=True)),
                ('cit_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cit_modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DMS_District',
            fields=[
                ('dis_id', models.AutoField(primary_key=True, serialize=False)),
                ('dis_name', models.CharField(max_length=255)),
                ('dis_is_deleted', models.BooleanField(default=False)),
                ('dis_added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('dis_added_date', models.DateTimeField(auto_now=True)),
                ('dis_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('dis_modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DMS_State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255)),
                ('state_is_deleted', models.BooleanField(default=False)),
                ('state_added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('state_added_date', models.DateTimeField(auto_now=True)),
                ('state_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('state_modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DMS_Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=255)),
                ('dep_is_central', models.BooleanField(default=False)),
                ('dep_is_deleted', models.BooleanField(default=False)),
                ('dep_added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('dep_added_date', models.DateTimeField(auto_now=True)),
                ('dep_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('dep_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('cit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_city')),
                ('dis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_district')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_state')),
            ],
        ),
        migrations.CreateModel(
            name='DMS_Group',
            fields=[
                ('grp_id', models.AutoField(primary_key=True, serialize=False)),
                ('grp_code', models.CharField(max_length=100)),
                ('permission_status', models.IntegerField(blank=True, null=True)),
                ('grp_name', models.CharField(max_length=255)),
                ('grp_is_deleted', models.BooleanField(default=False)),
                ('grp_added_date', models.DateTimeField(auto_now=True)),
                ('grp_added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('grp_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('grp_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_department')),
            ],
        ),
        migrations.CreateModel(
            name='DMS_Module',
            fields=[
                ('mod_id', models.AutoField(primary_key=True, serialize=False)),
                ('mod_code', models.CharField(max_length=100)),
                ('mod_name', models.CharField(max_length=255)),
                ('mod_is_deleted', models.BooleanField(default=False)),
                ('mod_added_date', models.DateTimeField(auto_now=True)),
                ('mod_added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('mod_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('mod_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('mod_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_group')),
            ],
        ),
        migrations.CreateModel(
            name='DMS_Permission',
            fields=[
                ('per_id', models.AutoField(primary_key=True, serialize=False)),
                ('mod_submod_per', models.TextField()),
                ('screen_no', models.CharField(max_length=100)),
                ('per_is_deleted', models.BooleanField(default=False)),
                ('per_added_date', models.DateTimeField(auto_now=True)),
                ('per_added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('per_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('per_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('grp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_group')),
            ],
        ),
        migrations.AddField(
            model_name='dms_district',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_state'),
        ),
        migrations.CreateModel(
            name='DMS_SubModule',
            fields=[
                ('sub_mod_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_mod_name', models.CharField(max_length=255)),
                ('sub_mod_is_deleted', models.BooleanField(default=False)),
                ('sub_mod_added_date', models.DateTimeField(auto_now=True)),
                ('sub_mod_added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_mod_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('sub_mod_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_module')),
            ],
        ),
        migrations.CreateModel(
            name='DMS_Action',
            fields=[
                ('ac_id', models.AutoField(primary_key=True, serialize=False)),
                ('ac_name', models.CharField(max_length=255)),
                ('ac_is_deleted', models.BooleanField(default=False)),
                ('ac_added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('ac_added_date', models.DateTimeField(auto_now=True)),
                ('ac_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('ac_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_submodule')),
            ],
        ),
        migrations.CreateModel(
            name='DMS_Tahsil',
            fields=[
                ('tah_id', models.AutoField(primary_key=True, serialize=False)),
                ('tah_name', models.CharField(max_length=255)),
                ('tah_is_deleted', models.BooleanField(default=False)),
                ('tah_added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('tah_added_date', models.DateTimeField(auto_now=True)),
                ('tah_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('tah_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('dis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_district')),
            ],
        ),
        migrations.AddField(
            model_name='dms_department',
            name='tah_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_tahsil'),
        ),
        migrations.AddField(
            model_name='dms_city',
            name='tah_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_tahsil'),
        ),
        migrations.CreateModel(
            name='DMS_WebLogin',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_login_time', models.DateTimeField(auto_now=True)),
                ('emp_logout_time', models.DateTimeField(blank=True, null=True)),
                ('log_status', models.CharField(max_length=50)),
                ('log_added_date', models.DateTimeField(auto_now=True)),
                ('log_added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('log_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
